# version: '3.8'

# services:

#   kong-database:
#     image: postgres:13
#     container_name: kong-database
#     environment:
#       POSTGRES_USER: kong
#       POSTGRES_DB: kong
#       POSTGRES_PASSWORD: kong
#     ports:
#       - "5432:5432"
#     volumes:
#       - kong-data:/var/lib/postgresql/data

#   kong-migrations:
#     image: kong:3.4
#     depends_on:
#       - kong-database
#     environment:
#       KONG_DATABASE: postgres
#       KONG_PG_HOST: kong-database
#       KONG_PG_USER: kong
#       KONG_PG_PASSWORD: kong
#     command: kong migrations bootstrap
#     restart: on-failure

#   kong:
#     image: kong:3.4
#     container_name: kong
#     depends_on:
#       - kong-database
#       - kong-migrations
#     environment:
#       KONG_DATABASE: postgres
#       KONG_PG_HOST: kong-database
#       KONG_PG_USER: kong
#       KONG_PG_PASSWORD: kong
#       KONG_ADMIN_LISTEN: "0.0.0.0:8001"
#       KONG_PROXY_ACCESS_LOG: /dev/stdout
#       KONG_ADMIN_ACCESS_LOG: /dev/stdout
#       KONG_PROXY_ERROR_LOG: /dev/stderr
#       KONG_ADMIN_ERROR_LOG: /dev/stderr
#     ports:
#       - "8000:8000"  # Proxy (public)
#       - "8001:8001"  # Admin API (private or dev)
#     restart: always

#   konga:
#     image: pantsel/konga:latest
#     container_name: konga
#     ports:
#       - "1337:1337"
#     environment:
#       DB_ADAPTER: postgres
#       DB_HOST: kong-database
#       DB_PORT: 5432
#       DB_USER: kong
#       DB_PASSWORD: kong
#       DB_DATABASE: konga
#       NODE_ENV: production
#       KONGA_DB_AUTO_MIGRATE: 'true'
#     depends_on:
#       - kong-database
#     restart: always

#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: backend
#     ports:
#       - "3000:3000"
#     restart: always

# volumes:
#   kong-data:

version: "3"

networks:
  kong-net:
    driver: bridge

services:

  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6
    restart: always
    networks:
      - kong-net
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong        # ✅ Required for proper startup
      POSTGRES_DB: kong
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong:latest
    command: "kong migrations bootstrap"
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    depends_on:
      - kong-database

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:latest
    restart: always
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-migration
      - kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8000:8000"
      - "8001:8001"

  #######################################
  # Konga database prepare
  #######################################
  konga-prepare:
    image: pantsel/konga:next
    command: "-c prepare -a postgres -u postgresql://kong:kong@kong-database:5432/konga_db"
    networks:
      - kong-net
    restart: on-failure
    depends_on:
      - kong-database

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga:next
    restart: always
    networks:
      - kong-net
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_USER: kong
      DB_PASSWORD: kong            # ✅ Required for Konga to connect to Postgres
      DB_DATABASE: konga_db
      NODE_ENV: production
      TOKEN_SECRET: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
    depends_on:
      - kong-database
    ports:
      - "1337:1337"

    
